"""Add launch table and satellite launch_id

Revision ID: 1a8d97c5cef0
Revises: 
Create Date: 2026-01-15 00:22:03.849721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8d97c5cef0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('launches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cospar_id', sa.String(length=20), nullable=False),
    sa.Column('mission_name', sa.String(length=100), nullable=True),
    sa.Column('launch_date', sa.DateTime(), nullable=True),
    sa.Column('launch_site', sa.String(length=100), nullable=True),
    sa.Column('rocket_type', sa.String(length=50), nullable=True),
    sa.Column('launch_success', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('launches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_launches_cospar_id'), ['cospar_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_launches_launch_date'), ['launch_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_launches_mission_name'), ['mission_name'], unique=False)

    with op.batch_alter_table('satellites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('launch_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_satellites_launch_id'), ['launch_id'], unique=False)
        batch_op.create_foreign_key('fk_satellites_launch_id', 'launches', ['launch_id'], ['id'])

    with op.batch_alter_table('tle_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tle_history', schema=None) as batch_op:
        batch_op.drop_column('source')

    with op.batch_alter_table('satellites', schema=None) as batch_op:
        batch_op.drop_constraint('fk_satellites_launch_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_satellites_launch_id'))
        batch_op.drop_column('launch_id')

    with op.batch_alter_table('launches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_launches_mission_name'))
        batch_op.drop_index(batch_op.f('ix_launches_launch_date'))
        batch_op.drop_index(batch_op.f('ix_launches_cospar_id'))

    op.drop_table('launches')
    # ### end Alembic commands ###
